Scott
isxbot/software-assurance pull request #21
Opened 2019-09-10 07:02 UTC by sreiling72

Take a look at the operational environment and security history parts, and let me know. I looked at two other projects that made the HOF to get an idea on how those sections are structured. Thank you!

2019-09-10 14:51 UTC, asimonson17 requested changes
The first part of this down to the end of the API's is really redundant to the description of Kafka for my portion.

2019-09-10 19:38 UTC, sreiling72 commented
@asimonson17 : You say it's redundant down through the end of my listing of the APIs, but I don't see where you describe the APIs in detail, and I also don't see where you define _topics_ and _records_ (which are part of that block)? 
  I wanted to include a overview of Kafka's functions, as seen in the first paragraph; that part is somewhat redundant, and I apologize for that.  I just wanted to provide a context for the rest of the section.  I can eliminate it, if you like?

 @isxbot : Also, I do use a hypothetical operational environment involving a stock exchange platform, and  I think that is a great example of an environment in which a message broker is critical, despite the fact that none of Kafka users are in that sector.  Cloudflare analytics is the other example I used; they are a Kafka consumer.

2019-09-10 21:19 UTC, asimonson17 commented
Hey Scott, maybe we can position yours in-between my sections that way it flows the way yours does? I mention the API's in more of an "these are the uses it has: Storage, Messaging, Stream processor, etc". If they are different than what I mention, that's cool too. Your description of Kafka may even be better than mine. If that's the case and others think so, we could work it that way as well.

2019-09-10 22:01 UTC, sreiling72 commented
@asimonson17  @isxbot  @samuelkissner check out the changes made, and let me know if it is less redundant, and more on-point with the op-env section needs. Thanks!

2019-09-10 23:45 UTC, samuelkissner approved these changes

2019-09-11 00:20 UTC, asimonson17 approved these changes
Looks good!

2019-09-11 13:18 UTC, merged